//
//  BubbleCloud.m
//  Picapp
//
//  Created by Vumai on 4/13/15.
//  Copyright (c) 2015 Uvney. All rights reserved.

#import "BubbleCloud.h"


@implementation BubbleCloud

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCloudWithFrame: (CGRect)frame boder: (CGFloat)boder bgColor:(UIColor*)bgColor bdColor:(UIColor*)bdColor
{
    //// Color Declarations
    UIColor* backgroundColor = bgColor;
    UIColor* boderColor = bdColor;

    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50887 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09197 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51941 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07616 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51169 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08645 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51520 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08114 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57421 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04786 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53405 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05885 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55417 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04918 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58895 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04842 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57916 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04754 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58410 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04772 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04801 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04825 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04812 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59339 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04793 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64182 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06300 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61072 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04656 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62806 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05143 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64583 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06668 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64322 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06418 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64456 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06541 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66682 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10675 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65402 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07196 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66145 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08539 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67318 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14657 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66984 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11879 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67195 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13231 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74159 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12685 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69395 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12865 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71983 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12085 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75216 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13106 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12786 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74878 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12926 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76408 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13997 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75667 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13347 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76065 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13648 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80857 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16793 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.78056 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14423 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.79624 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15364 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82015 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18485 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.81315 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17324 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.81701 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17893 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24245 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82793 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19560 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83221 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21546 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82590 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28634 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25669 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.82891 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27158 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87121 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28394 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84016 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27913 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.85626 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27843 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88114 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28863 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87459 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28519 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87791 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28675 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88470 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29085 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.88234 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28933 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.88352 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29007 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91511 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30818 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89556 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29348 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90606 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29929 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92596 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31756 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91907 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31035 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92271 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31353 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94566 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34384 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93419 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32241 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33163 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37425 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95184 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35127 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.95663 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36174 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.96204 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.96754 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39680 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.96833 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42247 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95264 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46757 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.96085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45243 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.95772 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46004 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94475 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47890 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95031 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47159 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94768 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47539 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92230 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49632 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93803 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48695 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.93038 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49274 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89640 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51048 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91433 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50164 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90562 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50636 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92839 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55982 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.90938 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52369 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92075 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54073 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.93051 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63452 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94026 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58952 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94026 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61710 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92386 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65372 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.92988 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64318 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92763 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64965 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89368 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67990 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91876 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66816 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90843 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67789 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86738 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67601 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.88534 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68103 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87639 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67959 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87216 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69451 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.86926 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68211 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68830 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87073 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75570 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87747 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72007 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74142 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84775 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79677 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.86838 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77162 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78629 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75659 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79222 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82190 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81775 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.78371 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81503 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75667 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79494 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75153 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86848 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76361 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81544 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76239 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84236 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69548 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92619 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73919 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89815 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91930 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61845 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94234 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67189 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94186 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64481 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94709 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54832 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92621 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59438 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94539 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.56993 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94013 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49513 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86523 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52916 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92265 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51027 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90236 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92106 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45514 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92069 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39578 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94534 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31841 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91190 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92003 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32816 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91703 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28139 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87554 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30304 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90381 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.29062 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89123 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27582 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87893 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.27954 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87672 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.27769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87785 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26351 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89156 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.27176 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88365 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26765 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88788 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.22289 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90605 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.24832 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90504 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.23451 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90948 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17591 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88124 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.20421 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90789 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.18806 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89890 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.12816 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74183 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.13744 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85635 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.11997 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80129 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.09290 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73289 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12181 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73872 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.09811 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73751 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.07277 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71501 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.08283 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72395 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.08076 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72446 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04610 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66045 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06040 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70041 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.04819 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66679 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04636 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59455 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.03899 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63890 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.03962 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61605 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.07348 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54682 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.05176 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57731 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.06108 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56095 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.05766 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52734 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06639 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53984 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.06093 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53314 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50946 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.05263 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51840 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.05088 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51519 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03249 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46478 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.03972 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49570 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.03525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47853 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.08721 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31386 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.02012 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.04457 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34295 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10376 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30483 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.09254 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31023 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.09807 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30723 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.14789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29796 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.11779 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29893 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.13276 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29675 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.16288 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19304 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.14206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25977 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.14738 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22228 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19636 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15438 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17118 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17740 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.18239 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16413 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32589 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16851 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.23536 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12717 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.28549 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13468 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15198 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32712 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16293 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32833 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15741 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34637 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09723 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33482 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12720 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11077 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34891 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09113 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34723 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09513 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34808 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09311 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34963 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08942 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38991 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04474 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35392 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07927 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05154 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42011 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02686 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40097 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40375 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02910 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50887 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09197 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46047 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02135 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49219 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04673 * CGRectGetHeight(frame))];
    [bezierPath closePath];
    [backgroundColor setFill];
    [bezierPath fill];
    [boderColor setStroke];
    bezierPath.lineWidth = boder;
    [bezierPath stroke];
    
    
    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.20089 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.29286 + 0.5), floor(CGRectGetWidth(frame) * 0.76786 + 0.5) - floor(CGRectGetWidth(frame) * 0.20089 + 0.5), floor(CGRectGetHeight(frame) * 0.67857 + 0.5) - floor(CGRectGetHeight(frame) * 0.29286 + 0.5))];
    [backgroundColor setFill];
    [rectanglePath fill];

}

+ (void)drawCircleArrowWithFrame: (CGRect)frame boder: (CGFloat)boder bgColor:(UIColor*)bgColor bdColor:(UIColor*)bdColor
{
    //// Color Declarations
    UIColor* backgroundColor = bgColor;
    UIColor* boderColor = bdColor;

    //// Oval 2 Drawing
    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.09722 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.03077 + 0.5), floor(CGRectGetWidth(frame) * 0.93056 + 0.5) - floor(CGRectGetWidth(frame) * 0.09722 + 0.5), floor(CGRectGetHeight(frame) * 0.96923 + 0.5) - floor(CGRectGetHeight(frame) * 0.03077 + 0.5))];
    [backgroundColor setFill];
    [oval2Path fill];
    [boderColor setStroke];
    oval2Path.lineWidth = boder;
    [oval2Path stroke];
}

+ (void)drawCircleWithFrame: (CGRect)frame bgColor:(UIColor*)bgColor
{
    //// Color Declarations
    UIColor* backgroundColor = bgColor;

    //// Oval 2 Drawing
    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.09722 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.03077 + 0.5), floor(CGRectGetWidth(frame) * 0.93056 + 0.5) - floor(CGRectGetWidth(frame) * 0.09722 + 0.5), floor(CGRectGetHeight(frame) * 0.96923 + 0.5) - floor(CGRectGetHeight(frame) * 0.03077 + 0.5))];
    [backgroundColor setFill];
    [oval2Path fill];
}

@end
